# Local development environment
services:
  articles-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./databases/articles.sql:/docker-entrypoint-initdb.d/init.sql
      - articles-data:/var/lib/postgresql/data

  books-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./databases/books.sql:/docker-entrypoint-initdb.d/init.sql
      - books-data:/var/lib/postgresql/data

volumes:
  articles-data:
  books-data:
