version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - ARTICLES_DB_NAME=articles
      - ARTICLES_DB_USER=postgres
      - ARTICLES_DB_PASSWORD=postgres
      - BOOKS_DB_NAME=books
      - BOOKS_DB_USER=postgres
      - BOOKS_DB_PASSWORD=postgres
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - articles-db
      - books-db

  articles-db:
    image: postgres:15
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./databases/articles.sql:/docker-entrypoint-initdb.d/init.sql
      - articles-data:/var/lib/postgresql/data

  books-db:
    image: postgres:15
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./databases/books.sql:/docker-entrypoint-initdb.d/init.sql
      - books-data:/var/lib/postgresql/data

volumes:
  articles-data:
  books-data:
