# Local development environment
services:
  blog-db:
    image: postgres:16-alpine
    environment:
      DB_NAME: blog
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./databases/blog.sql:/docker-entrypoint-initdb.d/init.sql
      - blog-data:/var/lib/postgresql/data

volumes:
  blog-data:
