services:
  - type: web
    name: personal-web-backend
    runtime: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DB_HOST
        fromDatabase:
          name: personal-web-db
          property: host
      - key: ARTICLES_DB_NAME
        value: personal_web_db
      - key: ARTICLES_DB_USER
        fromDatabase:
          name: personal-web-db
          property: user
      - key: ARTICLES_DB_PASSWORD
        fromDatabase:
          name: personal-web-db
          property: password
      - key: BOOKS_DB_NAME
        value: personal_web_db
      - key: BOOKS_DB_USER
        fromDatabase:
          name: personal-web-db
          property: user
      - key: BOOKS_DB_PASSWORD
        fromDatabase:
          name: personal-web-db
          property: password
      - key: AUTH_DB_NAME
        value: personal_web_db
      - key: AUTH_DB_USER
        fromDatabase:
          name: personal-web-db
          property: user
      - key: AUTH_DB_PASSWORD
        fromDatabase:
          name: personal-web-db
          property: password
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: personal-web-backend
          property: url

databases:
  - name: personal-web-db
    databaseName: personal_web_db
    plan: free
    ipAllowList: []
