services:
  # Web Service
  - type: web
    name: personal-web-backend
    runtime: node
    region: ohio
    plan: starter
    buildCommand: npm install && npm run init-db && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: personal-web-backend
          property: url
      # Articles DB
      - key: ARTICLES_DB_NAME
        fromDatabase:
          name: articles-db
          property: database
      - key: ARTICLES_DB_USER
        fromDatabase:
          name: articles-db
          property: user
      - key: ARTICLES_DB_PASSWORD
        fromDatabase:
          name: articles-db
          property: password
      - key: ARTICLES_DB_PORT
        value: 5432
      - key: DB_HOST
        fromDatabase:
          name: articles-db
          property: host
      # Books DB
      - key: BOOKS_DB_NAME
        fromDatabase:
          name: books-db
          property: database
      - key: BOOKS_DB_USER
        fromDatabase:
          name: books-db
          property: user
      - key: BOOKS_DB_PASSWORD
        fromDatabase:
          name: books-db
          property: password
      - key: BOOKS_DB_PORT
        value: 5432
      # Auth DB
      - key: AUTH_DB_NAME
        fromDatabase:
          name: auth-db
          property: database
      - key: AUTH_DB_USER
        fromDatabase:
          name: auth-db
          property: user
      - key: AUTH_DB_PASSWORD
        fromDatabase:
          name: auth-db
          property: password
      - key: AUTH_DB_PORT
        value: 5432

databases:
  # Databases
  - name: articles-db
    databaseName: articles
    user: articles_user
    ipAllowList: []

  - name: books-db
    databaseName: books
    user: books_user
    ipAllowList: []

  - name: auth-db
    databaseName: auth
    user: auth_user
    ipAllowList: []
